schemaDir: ./schemas

registryDir: /Users/bas/repos/projects/catafolk-registry

excludedCorpora:
  # - boehme-altdeutsches-liederbuch
  # - boehme-volksthumliche-lieder
  - bronson-child-ballads
  # - creighton-nova-scotia
  # - densmore-choctaw
  # - densmore-maidu
  # - densmore-menominee
  # - densmore-nootka
  # - densmore-northern-ute
  - densmore-ojibway
  # - densmore-papago
  - densmore-pawnee
  # - densmore-pueblo
  # - densmore-teton-sioux
  # - erk-deutscher-liederhort 
  # - essen-china-han
  # - essen-china-natmin
  # - essen-china-shanxi
  # - essen-china-xinhua
  # - finnish-folk-tunes
  # - haydn-scottish-songs
  # - natural-history-of-song
  # - pinck-verklingende-weisen
  # - sagrillo-ireland
  # - sagrillo-luxembourg
